require: rubocop-rspec

AllCops:
  TargetRubyVersion: "2.7.5"
  Exclude:
    - '**/bin/spring'
    - '**/bin/setup'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
    - 'config/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'vendor/**/**'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'
    - 'argon_call_number_search.gemspec'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/**'